#!/bin/bash

cd "$(tmux display-message -p "#{pane_current_path}")"

CLEAN_COLOR="#[fg=blue]"
STAGED_COLOR="#[fg=cyan]"
DIRTY_COLOR="#[fg=yellow]"
RESET_COLOR="#[fg=default]"

GIT_SYMBOL='\ue708'
STAGED_SYMBOL='\uf632'
UNSTAGED_SYMBOL='\uf658'
UNTRACKED_SYMBOL='\ufcc1'

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"

if [[ -n "$BRANCH" ]]
then
  STAGED="$(git diff --cached --numstat | wc -l)"
  UNSTAGED="$(git diff --numstat | wc -l)"
  UNTRACKED="$(git ls-files --exclude-standard --other | wc -l)"

  OUTPUT="$GIT_SYMBOL $BRANCH | $STAGED $STAGED_SYMBOL $UNSTAGED $UNSTAGED_SYMBOL $UNTRACKED $UNTRACKED_SYMBOL"

  if [[ "${#UNTRACKED}" > 0 || "${#UNSTAGED}" > 0 ]]
  then
    COLOR="$DIRTY_COLOR"
  elif [[ "${#STAGED}" > 0 ]]
  then
    COLOR="$STAGED_COLOR"
  else
    COLOR="$CLEAN_COLOR"
  fi

  printf "$COLOR$OUTPUT$RESET_COLOR"
fi
